### ISSUE TITLE
Stuck on anime page when i clicked

### ISSUE THREAD

**Issue by hshshs2** [cywteow/gogoanime#10]
Although i can use Seren&Ezra normally, i cant use Gogo rn, this is the error log i saw.

         -NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error type: <class 'request.exceptions.ConnectionError'>
     Error Contents: HTTPSConnectionPool(host='ajax.gogo-load.com', port=443): Max retries exceeded with url:/ajax/load-list-episode?ep_start=1080&ep_end=1031&id=171&default_ep=0&alias=onepiece(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x93654300>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
             Traceback (most recent call last):
 File "/addons/script.module.urllib3/lib/urllib3/connection.py", line 174, in _new_conn
 conn = connection.create_connection(

File "/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 95, in create_connection
raise err

File "/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 85, in create_connection
sock.connect(sa)

OSError: [Errno 101] Network is unreachable

any fix? thanks

**Comment by cywteow** [comment]
Do you still have this problem?

**Comment by hshshs2** [comment]
it still persist every sunday, idk if the gogoanime does maintenance on that day, but the addon does work monday - saturday
