### ISSUE TITLE
resolveurl.plugins.lib error

### ISSUE THREAD

**Issue by crimson53v-ux2** [cywteow/gogoanime#5]
I seem to be getting resolveurl plugin errors randomly (as in the add-on can't get the video url's), it also fixes itself randomly after i use kodi for some time (sometimes it takes days other times minutes), cleanly reinstalling kodi seems to fix it too (not 100% sure about this tough), replacing resolveurl plugin from a different source doesn't seem to help.
(other add-ons that use resoveurl don't seem to have any problem running)
Do you have any idea what might be causing this?

Here's the log:

> 2022-05-09 17:12:19.217 T:4304    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'resolveurl.plugins.lib'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\crims\AppData\Roaming\Kodi\addons\plugin.video.gogoanime\addon.py", line 447, in <module>
                                                       plugin.run()
                                                     File "C:\Users\crims\AppData\Roaming\Kodi\addons\script.module.reroutingpy3\lib\rerouting.py", line 61, in run
                                                       func(**match.groupdict())
                                                     File "C:\Users\crims\AppData\Roaming\Kodi\addons\plugin.video.gogoanime\addon.py", line 330, in play_episode
                                                       sources.append(resolveurl.HostedMediaFile(url=server['data-video'], title=title))
                                                     File "C:\Users\crims\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 86, in __init__
                                                       self.__resolvers = self.__get_resolvers(include_disabled, include_universal, include_popups)
                                                     File "C:\Users\crims\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 104, in __get_resolvers
                                                       klasses = resolveurl.relevant_resolvers(self._domain, include_universal=include_universal,
                                                     File "C:\Users\crims\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 69, in relevant_resolvers
                                                       load_external_plugins()
                                                     File "C:\Users\crims\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 62, in load_external_plugins
                                                       imp = __import__(mod_name, globals(), locals())
                                                     File "C:\Users\crims\AppData\Roaming\Kodi\addons\plugin.video.gogoanime\resources/lib/resolveurl/plugins\fcdn.py", line 20, in <module>
                                                       from resolveurl.plugins.lib import helpers
                                                   ModuleNotFoundError: No module named 'resolveurl.plugins.lib'
                                                   -->End of Python script error report<--

**Comment by cywteow** [comment]
It was broken yesterday and I just updated it today. Try updating to gogoanime 2.0.4

**Comment by crimson53v-ux2** [comment]
Yup it just updated and fixed itself, i thought it must be something on my end.
I'm a huge fan of your work and i'm sorry for wasting your time with this, have a great day.
